/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    events: Event;
    articles: Article;
    testimonials: Testimonial;
    sponsors: Sponsor;
    faqs: Faq;
    media: Media;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    events: EventsSelect<false> | EventsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    home: Home;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Upcoming events shown in the Programs / Events grid.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  title: string;
  type: 'Workshop' | 'Seminar' | 'Conference' | 'Corporate Olympics';
  date: string;
  city: string;
  /**
   * Card image (~600×400). Falls back to a placeholder if empty.
   */
  image?: (string | null) | Media;
  /**
   * Optional fallback image URL if no media is uploaded yet.
   */
  externalImage?: string | null;
  /**
   * Registration link.
   */
  registerUrl?: string | null;
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe the image for screen readers & SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Insight / blog posts shown in the Latest Articles section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  title: string;
  author: string;
  category: string;
  /**
   * e.g. "6 min read"
   */
  readTime?: string | null;
  /**
   * Link to the full article.
   */
  url?: string | null;
  image?: (string | null) | Media;
  /**
   * Fallback image URL if no media uploaded.
   */
  externalImage?: string | null;
  /**
   * One featured article renders large. Others render in the side list.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Success stories. NOTE: seed data is placeholder — replace with real, attributed quotes before launch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  quote: string;
  name: string;
  /**
   * e.g. "Chief People Officer, [Organization]"
   */
  role?: string | null;
  rating?: number | null;
  avatar?: (string | null) | Media;
  /**
   * Fallback avatar URL.
   */
  externalAvatar?: string | null;
  /**
   * One featured testimonial renders in the large panel.
   */
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Partner / sponsor logos shown in the Trusted By marquee.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: string;
  name: string;
  /**
   * Transparent SVG/PNG. If empty, a placeholder icon + name is shown.
   */
  logo?: (string | null) | Media;
  url?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Frequently asked questions (accordion).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  question: string;
  answer: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: string | Sponsor;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  date?: T;
  city?: T;
  image?: T;
  externalImage?: T;
  registerUrl?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  author?: T;
  category?: T;
  readTime?: T;
  url?: T;
  image?: T;
  externalImage?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  rating?: T;
  avatar?: T;
  externalAvatar?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  heroBadge?: string | null;
  /**
   * Words revealed with a stagger. Toggle "gold" to highlight a word.
   */
  heroHeadline?:
    | {
        word: string;
        gold?: boolean | null;
        id?: string | null;
      }[]
    | null;
  heroSubheading?: string | null;
  heroPrimaryCtaLabel?: string | null;
  heroPrimaryCtaUrl?: string | null;
  heroSecondaryCtaLabel?: string | null;
  heroSecondaryCtaUrl?: string | null;
  heroImage?: (string | null) | Media;
  /**
   * Fallback hero image URL.
   */
  heroExternalImage?: string | null;
  /**
   * PLACEHOLDER numbers — replace with client figures. Shown in hero + Numbers section.
   */
  stats?:
    | {
        value: number;
        suffix?: string | null;
        label: string;
        /**
         * Lucide-style icon key. Available: certificate, network, engage, explore, expert, community, search, register, attend, grow, mission, vision, values, speakers, orgs, participants, events.
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  aboutEyebrow?: string | null;
  aboutHeading?: string | null;
  aboutLead?: string | null;
  aboutImage?: (string | null) | Media;
  aboutExternalImage?: string | null;
  aboutBadgeNumber?: string | null;
  aboutBadgeText?: string | null;
  mvv?:
    | {
        /**
         * Lucide-style icon key. Available: certificate, network, engage, explore, expert, community, search, register, attend, grow, mission, vision, values, speakers, orgs, participants, events.
         */
        icon?: string | null;
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  timeline?:
    | {
        year: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  whyEyebrow?: string | null;
  whyHeading?: string | null;
  whySubheading?: string | null;
  tracks?:
    | {
        audience: 'attendees' | 'sponsors';
        tag: string;
        heading: string;
        text: string;
        statValue?: string | null;
        statLabel?: string | null;
        image?: (string | null) | Media;
        externalImage?: string | null;
        points?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        /**
         * Lucide-style icon key. Available: certificate, network, engage, explore, expert, community, search, register, attend, grow, mission, vision, values, speakers, orgs, participants, events.
         */
        icon?: string | null;
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  journeyEyebrow?: string | null;
  journeyHeading?: string | null;
  journeySubheading?: string | null;
  journeySteps?:
    | {
        /**
         * Lucide-style icon key. Available: certificate, network, engage, explore, expert, community, search, register, attend, grow, mission, vision, values, speakers, orgs, participants, events.
         */
        icon?: string | null;
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  ctaEyebrow?: string | null;
  ctaHeading?: string | null;
  ctaText?: string | null;
  ctaPrimaryLabel?: string | null;
  ctaPrimaryUrl?: string | null;
  ctaSecondaryLabel?: string | null;
  ctaSecondaryUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  brandName?: string | null;
  brandTagline?: string | null;
  /**
   * Download Brochure link.
   */
  brochureUrl?: string | null;
  primaryNavCtaLabel?: string | null;
  primaryNavCtaUrl?: string | null;
  navLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  trustedLabel?: string | null;
  footerAbout?: string | null;
  contactEmail?: string | null;
  contactLocation?: string | null;
  newsletterHeading?: string | null;
  newsletterText?: string | null;
  social?:
    | {
        platform: 'x' | 'facebook' | 'instagram' | 'youtube' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroBadge?: T;
  heroHeadline?:
    | T
    | {
        word?: T;
        gold?: T;
        id?: T;
      };
  heroSubheading?: T;
  heroPrimaryCtaLabel?: T;
  heroPrimaryCtaUrl?: T;
  heroSecondaryCtaLabel?: T;
  heroSecondaryCtaUrl?: T;
  heroImage?: T;
  heroExternalImage?: T;
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        icon?: T;
        id?: T;
      };
  aboutEyebrow?: T;
  aboutHeading?: T;
  aboutLead?: T;
  aboutImage?: T;
  aboutExternalImage?: T;
  aboutBadgeNumber?: T;
  aboutBadgeText?: T;
  mvv?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  timeline?:
    | T
    | {
        year?: T;
        text?: T;
        id?: T;
      };
  whyEyebrow?: T;
  whyHeading?: T;
  whySubheading?: T;
  tracks?:
    | T
    | {
        audience?: T;
        tag?: T;
        heading?: T;
        text?: T;
        statValue?: T;
        statLabel?: T;
        image?: T;
        externalImage?: T;
        points?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  benefits?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  journeyEyebrow?: T;
  journeyHeading?: T;
  journeySubheading?: T;
  journeySteps?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  ctaEyebrow?: T;
  ctaHeading?: T;
  ctaText?: T;
  ctaPrimaryLabel?: T;
  ctaPrimaryUrl?: T;
  ctaSecondaryLabel?: T;
  ctaSecondaryUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  brandTagline?: T;
  brochureUrl?: T;
  primaryNavCtaLabel?: T;
  primaryNavCtaUrl?: T;
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  trustedLabel?: T;
  footerAbout?: T;
  contactEmail?: T;
  contactLocation?: T;
  newsletterHeading?: T;
  newsletterText?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}